DEVCommon:
  lakehouse_project_id: "sab-dev-dap-common-4288"
  pipeline_project_id:  "sab-dev-dap-common-4288"
  version:    "1.0"
  email:      "lorie.schmidt@sabre.com"
  extract_bucket: "ads_ads_extracts"
  start_date: 2021-12-10 00:00:00
  service_account  : "sab-dev-dap-ads-aafs@sab-dev-dap-data-pipeline-3013.iam.gserviceaccount.com"
DEV:
  lakehouse_project_id: "sab-dev-dap-lakehouse-1470"
  pipeline_project_id:  "sab-dev-dap-data-pipeline-3013"
  version:    "1.0"
  warning_recipient_email: "surendra.gangavaram.ctr@sabre.com"
  failure_recipient_email: "surendra.gangavaram.ctr@sabre.com"
  amex_recipient_email: "surendra.gangavaram.ctr@sabre.com"
  start_date: "2022-02-25"
  transaction_dt_plus_one_day: "None"
  service_account  : "sab-dev-dap-ads-aafs@sab-dev-dap-data-pipeline-3013.iam.gserviceaccount.com"
  pipeline_bucket_name  : "sab-dev-dap-ads-aafs-aafs_stg"
  ingress_bucket_name: "sab-dev-dap-ads-aafs-aafs_load"
  ingress_efg_bucket_name: "sab-dev-dap-efg-ingress"
  archive_bucket_name: "sab-dev-dap-ads-aafs-aafs_archive"
  lakehouse_dataset_id: "ads_aafs"
  pipeline_dataset_id: "ads_aafs_stg"
  schedule_interval: "*/31 14 11 * *"
  bq_dataset_location: "US"
  governance_project_id: "sab-dev-dap-governance1-8747"
  max_pcc_vendors: 200
  update_extract_table: "Y"
  number_of_days_to_keep_pcc_refresh_load_data: 90
  seconds_to_wait_between_dag_state_checks: "1*1*60"  # 30 minutes
  total_seconds_to_check_dag_state: "1*5*60"  # 4 hours total
CERT:
  lakehouse_project_id: "sab-cert-dap-lakehouse-8332"
  pipeline_project_id:  "sab-cert-dap-datapipeline-4618"
  version:    "1.0"
  warning_recipient_email: "adserverappstatus@sabre.com"
  failure_recipient_email: "DNAGCPPlatformSupport@sabre.com,adserverappstatus@sabre.com"
  extract_bucket: "sab-cert-dap-promospots_ads_extracts"
  start_date: "2022-02-25"
  transaction_dt_plus_one_day: "None"
  service_account: "sab-cert-dap-promospots-ads@sab-cert-dap-datapipeline-4618.iam.gserviceaccount.com"
  pipeline_bucket: "sab-cert-dap-promospots-ads-transaction_stg"
  ingress_bucket_name: "sab-cert-dap-promospots-ads-transaction_load"
  archive_bucket_name: "sab-cert-dap-promospots-ads-transaction_archival"
  lakehouse_dataset_id: "promospots_ads"
  pipeline_dataset_id: "promospots_ads_stg"
  kv_feed_prefix: "auction_kv_labels_feed-11303-"
  std_feed_prefix: "standard_feed-11303-"
  schedule_interval: "0 13 * * *" 
  bq_dataset_location: "US"
  apn_placements_sql_file: "ads_control_apn_cert_placements.sql"
  governance_project_id: "sab-cert-dap-governance-5011"
PROD:
  lakehouse_project_id: "sab-prod-dap-lakehouse-3582"
  pipeline_project_id:  "sab-prod-dap-datapipeline-2983"
  version:    "1.0"
  warning_recipient_email: "adserverappstatus@sabre.com"
  failure_recipient_email: "DNAGCPPlatformSupport@sabre.com,adserverappstatus@sabre.com"
  extract_bucket: "sab-prod-dap-promospots_ads_extracts"
  start_date: "2022-02-25"
  transaction_dt_plus_one_day: "None"
  service_account: "sab-prod-dap-promospots-ads@sab-prod-dap-datapipeline-2983.iam.gserviceaccount.com"
  pipeline_bucket: "sab-prod-dap-promospots-ads-transaction_stg"
  ingress_bucket_name: "sab-prod-dap-promospots-ads-transaction_load"
  archive_bucket_name: "sab-prod-dap-promospots-ads-transaction_archival"
  lakehouse_dataset_id: "promospots_ads"
  pipeline_dataset_id: "promospots_ads_stg"
  kv_feed_prefix: "auction_kv_labels_feed-10306-"
  std_feed_prefix: "standard_feed-10306-"
  schedule_interval: "0 13 * * *" 
  bq_dataset_location: "US"
  apn_placements_sql_file: "ads_control_apn_prod_placements.sql"
  governance_project_id: "sab-prod-dap-governance-8853"